### ISSUE TITLE
After uninstalling the branch name is still in the window title

### ISSUE THREAD

**Issue by jpweller** [wisetime-io/vscode-branch-in-window-title#18]
I uninstalled the extension after realizing I didn't need it, but the branch name is still in the window title. It does not remove the window title settings updated in the .vscode/settings.json

**Comment by grafogeum** [comment]
Same

**Comment by AnrDaemon** [comment]
Unfortunately, in absence of better options, the behavior of the extension is based on direct modification of the relevant workspace setting.
To remove the branch name after uninstalling the extension, manually edit (or reset) the `window.title` setting.

**Comment by grafogeum** [comment]
already solved by thank for response, it was annoying hopefully now if i forgot there is info here so thanks 👍🏼

**Comment by joshuaiz** [comment]
Still seeing the branch name in title bar after resetting the `window.title` setting. What am I missing here?

**Comment by AnrDaemon** [comment]
Double check that you reset both user and workspace variants.

**Comment by joshuaiz** [comment]
Thanks for this - got it sorted.
